(defproject webapp "0.1.0-SNAPSHOT"
  :description "webapp"
  :dependencies [[org.clojure/clojure "1.10.1"]
                 [ring "1.8.0"]
                 [ring-middleware-format "0.7.4"]
                 [ring/ring-defaults "0.3.2"]
                 [metosin/muuntaja "0.6.6"]
                 [metosin/reitit "0.4.2"]
                 [metosin/jsonista "0.2.5"]
                 [hiccup "1.0.5"]
                 [com.stuartsierra/component "1.0.0"]
                 [aero "1.1.6"]
                 [com.layerware/hugsql "0.5.1"]
                 [hikari-cp "2.11.0"]
                 [org.clojure/java.jdbc "0.7.11"]
                 [org.postgresql/postgresql "42.2.11"]
                 [camel-snake-kebab "0.4.1"]
                 [nilenso/mailgun "0.2.3"]
                 [ragtime "0.8.0"]
                 [buddy "2.0.0"]
                 [crypto-random "1.2.0"]]
  :profiles {:dev {:dependencies [[reloaded.repl "0.2.4"]]
                   :source-paths ["dev"]
                   :repl-options {:init-ns user}}}
  :main webapp.core)
